apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: database-template
  title: AWS Database Template
  description: Create a RDSInstance on AWS
  tags:
    - aws
    - rds
    - infrastructure
    - database
spec:
  owner: group:sre-team
  type: component

  parameters:
    - title: Provide some simple information
      required:
        - system
        - lifecycle
        - owner
      properties:
        system:
          title: System
          type: string
          description: System of the component
          ui:field: EntityPicker
          ui:options:
            allowedKinds:
              - System
            defaultKind: System 
        componet:
          title: Component
          type: string
          description: Component to create resource
          ui:field: ComponentPicker
          ui:options:
            allowedKinds:
              - Component            
        lifecycle:
          title: Lifecycle
          description: 'Application lifecycle'
          type: string
          default: experimental
          enum:
            - deprecated
            - experimental
            - production                         
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group

    - title: Infrastructure
      properties:      
        env:
          title: Environment
          description: 'Environment to create resources'
          type: string
          default: dev
          enum:
            - dev
            - stg
            - prd
        database:
          title: Database Parameters
          type: object
          properties:         
            type:
              enum:
              - MySQL
              - Postgres 
        dryRun:
          title: Only perform a dry run, don't publish anything
          type: boolean
          default: false

    - id: fetch-template
      name: Fetch RDS Templates
      action: fetch:template
      if: ${{ parameters.dryRun == false }}
      input:
        targetPath: ./rds
        url: https://github.com/diegoluisi/backstage-catalog/tree/main/devxp/skeleton/crossplane/rds
        values:
          system: ${{ parameters.system }}
          owner: ${{ parameters.owner }}
          env: ${{ parameters.env }}

    - id: open-pr
      name: "Open PR in GitOps Repository"
      action: publish:github:pull-request
      if: ${{ parameters.dryRun == false }}
      input:
        repoUrl: github.com?repo=crossplane-resources&owner=diegoluisi
        branchName: create-db-${{ parameters.system }}
        title: ':robot: [backstage-bot] Create new App ${{ parameters.system }}'
        description: |
          # New project: ${{ parameters.system }}
          ${{ parameters.description if parameters.description }}
        sourcePath: rds
        targetPath: resources/aws/apps/

    # - id: register
    #   name: Register Application in Catalog
    #   action: catalog:register
    #   if: ${{ parameters.dryRun !== true }}
    #   input:
    #     repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
    #     catalogInfoPath: "/catalog-info.yaml"

  output:
    links:
      - title: Go to Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Go to GitOps Pull Request
        url: ${{ steps.kube-pr.output.remoteUrl }}        
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}        