apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: bob
  description: Back Office System
  namespace: devxp-tech
  tags:
    - backoffice
    - php
  # annotations:
  #   github.com/project-slug: diegoluisi/bob
spec:
  type: system
  owner: group:dev-team
  domain: backend
