---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: all-groups
  description: A collection of all Backstage example Groups
  namespace: devxp-tech
spec:
  owner: group:engineering
  targets:
    - ./groups/org.yaml
