---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: all-systems
  description: A collection of all Backstage example systems
  namespace: devxp-tech
spec:
  owner: group:engineering
  targets:
    - ./systems/*.yaml