apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: alice-api
  description: Hello World example for gRPC

spec:
  type: openapi
  lifecycle: production
  system: alice
  owner: group:dev-team
  providesApis:
    - alice.diegoluisi.eti.br/v1
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Artist API
      license:
        name: MIT
    servers:
      - url: http://artist.spotify.net/v1
    paths:
      /artists:
        get:
          summary: List all artists