---
apiVersion: v1
kind: Service
metadata:
  name: ${{values.system}}-svc
  namespace: ${{values.system}}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: ${{values.system}}.diegoluisi.eti.br
  labels:
    app: ${{values.system}}
    backstage.io/kubernetes-id: ${{values.system}}
spec:
  type: ClusterIP
  ports:
  - name: tcp-node
    port: 8080
  selector:
    app: ${{values.system}}

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: ${{values.system}}-canary
#   namespace: ${{values.system}}
#   annotations:
#     external-dns.alpha.kubernetes.io/hostname: ${{values.system}}.${{values.system}}luisi.eti.br
#   labels:
#     app: ${{values.system}}
#     backstage.io/kubernetes-id: ${{values.system}}
# spec:
#   type: ClusterIP
#   ports:
#   - name: tcp-node
#     port: 8080
#   selector:
#     app: ${{values.system}}