apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: ${{values.component_id}}-hpa
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: ${{values.component_id}}
 minReplicas: 1
 maxReplicas: 4
 targetCPUUtilizationPercentage: 75