---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ${{values.system}}-vs
  namespace: ${{values.system}}
spec:
  gateways:
  - istio-system/istio-gateway
  hosts:
  - diego.diegoluisi.eti.br
  http:
  - name: primary
    route:
    - destination:
        host: ${{values.system}}-svc
      weight: 100