---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ${{values.component_id}}
    backstage.io/kubernetes-id: ${{values.component_id}}
  name: ${{values.component_id}}
  namespace: ${{values.component_id}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${{values.component_id}}
  template:
    metadata:
      labels:
        app: ${{values.component_id}}
        backstage.io/kubernetes-id: ${{values.component_id}}
    spec:
      containers:
      - image: diegoluisi/${{values.component_id}}:3c12d96f
        imagePullPolicy: IfNotPresent
        name: ${{values.component_id}}
        ports:
        - name: app-port
          containerPort: 8080
          protocol: TCP
        # livenessProbe:
        #   httpGet:
        #     path: /health-check/liveness
        #     port: app-port
        #   failureThreshold: 2
        #   periodSeconds: 10
        # startupProbe:
        #   httpGet:
        #     path: /health-check/readines
        #     port: app-port
        #   failureThreshold: 30
        #   periodSeconds: 10
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
