---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: ${{values.component_id}}
  labels:
    app: ${{values.component_id}}
    backstage.io/kubernetes-id: ${{values.component_id}}
spec:
  maxReplicas: 5
  minReplicas: 3
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: ${{values.component_id}}
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 75
        type: Utilization
    type: Resource