---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: ${{values.component_id}}
    backstage.io/kubernetes-id: ${{values.component_id}}
  name: ${{values.component_id}}
spec:
  finalizers:
  - kubernetes

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: ${{values.component_id}}.diegoluisi.eti.br
  labels:
    app: ${{values.component_id}}
    backstage.io/kubernetes-id: ${{values.component_id}}
  name: ${{values.component_id}}
  namespace: ${{values.component_id}}
spec:
  ports:
  - name: tcp-node
    port: 8080
  selector:
    app: ${{values.component_id}}
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ${{values.component_id}}
    backstage.io/kubernetes-id: ${{values.component_id}}
  name: ${{values.component_id}}
  namespace: ${{values.component_id}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${{values.component_id}}
  template:
    metadata:
      labels:
        app: ${{values.component_id}}
        backstage.io/kubernetes-id: ${{values.component_id}}
    spec:
      containers:
      - image: diegoluisi/${{values.component_id}}:3c12d96f
        imagePullPolicy: IfNotPresent
        name: ${{values.component_id}}
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: ${{values.component_id}}
spec:
  maxReplicas: 3
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 75
        type: Utilization
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ${{values.component_id}}

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ${{values.component_id}}
  namespace: ${{values.component_id}}
  labels:
    backstage.io/kubernetes-id: ${{values.component_id}}
spec:
  gateways:
  - istio-system/istio-gateway
  hosts:
  - ${{values.component_id}}.diegoluisi.eti.br
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: ${{values.component_id}}
        port:
          number: 8080
