---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ${{values.component_id}}
resources:
  - analyses.yaml
  - hpa.yaml
  - namespace.yaml
  - rollout.yaml
  - service.yaml
  - virtual-service.yaml