---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: ${{values.component_id}}
    backstage.io/kubernetes-id: ${{values.component_id}}
    # istio-injection: enabled
  name: ${{values.component_id}}
spec:
  finalizers:
  - kubernetes