apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: ${{values.component_id}}
spec:
  replicas: 3
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: ${{values.component_id}}
  template:
    metadata:
      labels:
        app: ${{values.component_id}}
    spec:
      containers:
      - name: ${{values.component_id}}
        image: diegoluisi/${{values.component_id}}:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 5m
  strategy:
    canary:
      canaryService: canary-demo-preview
      steps:
      - setWeight: 20
      - pause: {}
      - setWeight: 40
      - pause: {duration: 10}
      - setWeight: 60
      - pause: {duration: 10}
      - setWeight: 80
      - pause: {duration: 10}