---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: ${{values.component_id}}
  labels:
    app: ${{values.component_id}}
spec:
  strategy:
    canary:
      canaryService: ${{values.component_id}}-canary
      stableService: ${{values.component_id}}-stable
      trafficRouting:
        istio:
           virtualService:
            name: ${{values.component_id}}-vsvc
            routes:
            - primary
      steps:
      - setWeight: 25
      - pause: {duration: 20s} #{} pause indefinitely
      - setWeight: 50
      - pause: {duration: 20s}
      - setWeight: 75
      - pause: {duration: 20s}
      - setWeight: 100
      - pause: {duration: 20s}
  replicas: 4
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: ${{values.component_id}}
      version: 0.0.2
  template:
    metadata:
      labels:
        app: ${{values.component_id}}
        version: 0.0.2
    spec:
      containers:
      - name: ${{values.component_id}}
        image: diegoluisi/${{values.component_id}}:0.0.2
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "140m"
        livenessProbe:
          httpGet:
            path: /health-check/liveness
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health-check/readiness
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10