apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-web
  description: Backstage Frontend
  annotations:
    github.com/project-slug: devxp-tech/backstage
    backstage.io/kubernetes-namespace: backstage
    backstage.io/techdocs-ref: dir:.
    argocd/app-name: prd-backstage
    sonarqube.org/project-key: backstage
  tags:
    - web
    - frontend
  links:
    - url: https://backstage.diegoluisi.eti.br
      title: Backstage
      icon: cloud
spec:
  type: service
  lifecycle: production
  owner: group:sre-team
  system: backstage
  #dependsOn: ['component:bob-cache', 'component:bob-db', 'component:bob-queue']
  apiConsumedBy: ['system:backstage']
  providesApis:
    - backstage