apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: dev
  description: Developers Teams
spec:
  type: sub-department
  profile:
    displayName: Developers Team
    email: dev@devxp.io
    picture: https://avatars.dicebear.com/api/identicon/backstage@example.com.svg?background=%23fff&margin=25
  parent: engineering
  children: [devs-a]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: dev-a
  description: Developers Teams A
spec:
  type: team
  profile:
    displayName: Developers Team
    email: dev@devxp.io
    picture: https://avatars.dicebear.com/api/identicon/backstage@example.com.svg?background=%23fff&margin=25
  parent: dev
  children: []
---  
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: gritzko
spec:
  profile:
    displayName: Gritzko
    email: gritzko@devxp.io
    picture: https://avatars.dicebear.com/api/avataaars/nigel-manning@example.com.svg?background=%23fff
  memberOf: [dev, dev-a]