apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: engineering
  description: IT Engineering
spec:
  type: department
  profile:
    displayName: IT Engineering
    email: engineering@devxp.io
    picture: https://avatars.dicebear.com/api/identicon/backstage@example.com.svg?background=%23fff&margin=25
  parent: devxp
  children: [dev, ops]