apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: devxp
  description: The DevXP organization
  links:
    - url: http://www.devxp.io/
      title: Website
    - url: https://devxp.local/wiki/
      title: Intranet
spec:
  type: organization
  profile:
    displayName: DevXP Labs
    email: it@devxp.io
    picture: https://avatars.dicebear.com/api/identicon/info@example.com.svg?background=%23fff&margin=25
  children: [ops, dev, dba]
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: teams
  description: A collection of all Backstage example Groups
spec:
  targets:
    - ./dev.yaml  
    - ./ops.yaml
    - ./dba.yaml
